### ISSUE TITLE
Ideas - New Features

### ISSUE THREAD

**Issue by peter1000** [NuTyX/core#52]
Just a collection of some ideas: maybe one or the other might be useful and you want to implement them or I have implemented them and you want to back-port some.

- [ ] REUSE cards code https://github.com/NuTyX/houaphan/issues/52#issuecomment-196793041 https://github.com/NuTyX/houaphan/issues/52#issuecomment-198331897

- [ ] Support Arch pacman manager binary files <https://github.com/NuTyX/houaphan/issues/52#issuecomment-197219316>

- [ ] Change Pkgfile Header-format: to use proper variables https://github.com/NuTyX/houaphan/issues/52#issuecomment-198296313

I will add to this...

**Comment by peter1000** [comment]
### REUSE cards code

Maybe to reuse cards code for some parts is useful: e.g. parts of `pkgmk.passes` has a number of same functions.

Also the download part of  `runmebeforepass1` could with small adjustments make use of cards pkgmk.in download function.

#### TODO Idea

* Add option to cards `pkgmk.in` to pass an alternative *PKGMK_PKGFILE path*

    e.g. `-pf,  --pkgfile <file>      use alternative Pkgfile file`

* after that use a `Pkgfile` to download all sources: with `pkgmk --download-only`

**ADVANTAGE**: allows for multiple download location all out of the box and all the other advances features of cards pkgmk.in.

In `pkgmk_download_source.conf`

```
PKGMK_SOURCE_MIRRORS=(
    http://downloads.nutyx.org/current
    http://mirrors-usa.go-parts.com/lfs/lfs-packages/7.9/
)
```

In `Pkgfile_download_sources`

```
source=(
    http://download.savannah.gnu.org/releases/acl/acl-2.2.52.src.tar.gz
    http://download.savannah.gnu.org/releases/attr/attr-2.4.47.src.tar.gz
    ftp://ftp.astron.com/pub/file/file-5.25.tar.gz
    any_other_local_file_we_want_to_be_copied_to_the_sources_folder
)
```

**Comment by tnut** [comment]
Be aware that the article you refer to (build-pre, build-part-1, build-part-2, etc) is also usable from (should at least)  any other distributions. Nevertherless, new ideas are always welcomes

**Comment by peter1000** [comment]
My thought was like this: because to build nutyx one needs to do something like: `git clone git://github.com/NuTyX/houaphan.git current`

So there should not be much more work if one also clone cards.

Anyway, I will give this a try and let you know :+1:

**Comment by tnut** [comment]
:+1:  Thanks

**Comment by peter1000** [comment]
**REUSE cards code: I did test it** by adding an option `"  -pf,  --pkgfile <file>       use alternative Pkgfile file (a full path or only a name)"`

Seems tto work and does not need to change too much.

Only thing is: one would need to decide what to do in some cases like:

**What if the path to the `--pkgfile path_to_Pkgfile` is not in the current directory - should this be allowed**
 
If yes:

* Whats the value of: PKGMK_ROOT: `$PWD` or the actual dir of the Pkgfile
* Local sources: do they need to be in the current dir: `$PWD` or the actual dir of the Pkgfile
* Where are final cards pkg placed..
* What are the PKGREPO entries: only the Basename or full path?

Just some thoughts but otherwise it would work.

**Comment by peter1000** [comment]
### Support Arch pacman manager

this was my other idea a couple of days ago: I looked at the binary package files and it seems that one could add support for arch pacman package manager.

**Comment by tnut** [comment]
Fews probs, I see: 

- Cards takes some advantages of the C++ over C language: classes, classes heritage, virtual methods, exceptions, containers etc...
- API lib is transparently done (completly automated in the make file of the code) and it has already a good base.
- In 95 % of the cases, the runtime deps are automatically found. Means Cards have a clever way to analyse the library which where installed when the package is build. Even the build date of the deps is added which is for me a big PLUS.

- Shure they are features from the arch package manager we could implement like:
  - The signature of a package (today we have lets say... nothing)
  - The hooks,  means the PM should do some Actions on its own depending of the package
     I Thing of: info file, update Icon Cache, update font Cache, update Desktop entries menu, update the glib shemas files, etc

**Comment by peter1000** [comment]
I think I was not clear what I meant: I meant it might not need much to support pacman **additionally** to cards.

I'm still not really clear about the **runtime deps**  sorry.

* does it add them to the final binary pkg - so that if someone else install the binary pkg it also downloads and installs the **runtime deps** ?

* If that's so than this **runtime deps** could be different if you rebuild the pkg but have installed in the meantime some other pkgs?

**Comment by tnut** [comment]
- Yes it add them (the dependencies names) to the final binary package, so that if someone else install the binary pkg (via cards comand not via pkgadd as pkgadd do not deal with remotes packages) it also downloads and installs the runtime deps.
- NO this runtime deps should be the same if you follow the README method of the concerned collection and used the -a option of the script.


Now I'm confuse. Do you means ?
  1. Been able to instal archlinux package binaries with cards package manager
  2. Been able to install NuTyX packages binaries with pacman package manager ?

**Comment by peter1000** [comment]
I meant: **2. Be able to install NuTyX packages binaries with pacman package manager.** AND cards

if you inspect the binary packages there is not so much differences only a couple of additional files like:

e.g.: .PKGINFO  which looks like this:

```
# Generated by makepkg 5.0.1
# using fakeroot version 1.20.2
# Wed Mar 16 07:58:45 UTC 2016
pkgname = libglvnd
pkgver = 0.0.0.20160315-1
pkgdesc = The GL Vendor-Neutral Dispatch library
url = https://github.com/NVIDIA/libglvnd
builddate = 1458115125
packager = Felix Yan <felixonmars@archlinux.org>
size = 1620992
arch = x86_64
license = custom:BSD-like
depend = libxext
makedepend = xorg-server-devel
makedepend = git
makedepend = python2
```

it has also the: **builddate = 1458115125** :+1: 

Anyway most of the data are already available: so one could just add  this files 3 all together and maybe pacman and cards could use the same package.

Abyway, is just an idea not sure if this would work.

**Comment by peter1000** [comment]
Ok I gave it a fast manual try: 

**PACMAN** 

I added to a arch linux package 'wget' additional meta data from cards: pacman can still install it in Arch Linux

Removed wget from Arch linux, installed manipulated arch package: OK
```bash
[root@evo_virt 0_0_arch_makepkg_0_0]# pacman -R wget
checking dependencies...
:: spacefm-git_p optionally requires wget: plugin download

Packages (1) wget-1.17.1-1

Total Removed Size:  2.57 MiB

:: Do you want to remove these packages? [Y/n] 
:: Processing package changes...
(1/1) removing wget                                                                        [####################################################] 100%
[root@evo_virt 0_0_arch_makepkg_0_0]# wget
bash: wget: command not found
[root@evo_virt 0_0_arch_makepkg_0_0]# pacman -U wget-1.17.1-1-x86_64.pkg.tar.xz
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) wget-1.17.1-1

Total Installed Size:  2.57 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                             [####################################################] 100%
(1/1) checking package integrity                                                           [####################################################] 100%
(1/1) loading package files                                                                [####################################################] 100%
(1/1) checking for file conflicts                                                          [####################################################] 100%
(1/1) checking available disk space                                                        [####################################################] 100%
:: Processing package changes...
(1/1) installing wget                                                                      [####################################################] 100%
Optional dependencies for wget
    ca-certificates: HTTPS downloads [installed]
[root@evo_virt 0_0_arch_makepkg_0_0]# wget
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
[root@evo_virt 0_0_arch_makepkg_0_0]# 
```
**CARDS**

I added to a nutyx package additional metadata from the arch linux package

pkgadd  says: `pkgadd 1.99.9: invalid meta data in file wget1458143675x86_64.cards.tar.xz`

**Comment by tnut** [comment]
You says: Be able to install NuTyX packages binaries with pacman package manager. AND cards
And then I still don't see what's this feature will bring to NuTyX. As soon you deal with more then one PM you deal with more then one cache system (that's just one of the side 
effects)

**Comment by peter1000** [comment]
of course you are right that it would be probably a headache to deal with to different PM.

I'm also not sure what  this feature will bring to NuTyX ;) it's just an idea.

But what I could imagine is that for end users who only want the binaries they could simply use a pacman graphical front-end.

* **Developers, packagers and advanced linux users**: use probably ONLY *cards*
* **New users or users who only want binary packages**: use probably ONLY a *pacman front-end*

As I said: just an idea -even not sure if it would make sense to look into it.

**Comment by peter1000** [comment]
I just write some documentation on the Pkgfile header and thought: what does stop you to change the Pkgfile-header to proper variables?

**Comment by tnut** [comment]
You absolutly right, I was thinking to keep the compatibility with crux. And also think about making too many change it's not so good, I notist that by experience,.. users do not follows. I guess we can always add features but for shure not remove existings ones

**Comment by peter1000** [comment]
You could use for some variables the same names as Arch Linux PKGBUILD than you also do not need some of your (conversion code](https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1223)

about removing features: one could still use for some releases an internal converter until all Pkgfiles have been changed.
Of course: if the compatibility with crux is the reason than there is no point changing it :+1:

**Comment by tnut** [comment]
... yep, even personally I've never found inspirations in crux rezepts.. don't know why :)

**Comment by peter1000** [comment]
As much as I have seen you don't just copy Cruz packages without changing something: at least the Maintainer, Packager Tags.

So what I think: in that case why not remove also the `#` in front :)

**example current cards***

```
# Description: A set of utilities to manage software packages on NuTyX distribution.
# URL: https://github.com/NuTyX/cards
# Maintainer: tnut at nutyx dot org
# Packager: tnut at nutyx dot org

```

**Change to**

```
description="A set of utilities to manage software packages on NuTyX distribution."
url=https://github.com/NuTyX/cards
maintainer="tnut at nutyx dot org"
packager="tnut at nutyx dot org"
depends=()
```

Eventhough I think 2 separate tags for `maintainer` and `packager` are not really too helpful.

IF the variables are not found than still do Internally something  like: `get_pkgfile_variables`

```
get_pkgfile_variables() {
	local STRING KEY VALUE
	while read i;
	do
		STRING=`echo $i |grep \# | grep :|sed "s@^[ ,\t,#]*@@" `
		KEY=`echo $STRING|cut -d ":" -f1|sed "s@^[ ,\t,#]*@@"`
		VALUE=`echo $STRING|cut -d ":" -f1 --complement|sed "s@^[ ,\t,#]*@@"`
		if [ -z "$description" ]; then
			[ ! -z "`echo $KEY|grep -i desc`" ] && description=$VALUE
		fi
		if [ -z "$url" ]; then
			[ ! -z "`echo $KEY|grep -i url`" ] && url=$VALUE
		fi
		if [ -z "$packager" ]; then
			[ ! -z "`echo $KEY|grep -i pack`" ] && packager=$VALUE
		fi
		if [ -z "$maintainer" ]; then
			[ ! -z "`echo $KEY|grep -i main`" ] && maintainer=$VALUE
		fi

	done < $PKGMK_ROOT/$PKGMK_PKGFILE
}

```

**Comment by peter1000** [comment]
Anyway this is what I'm going to do: PKGFILE HEADER

```
description="A set of utilities to manage software packages on NuTyX distribution."
url=https://github.com/NuTyX/cards
maintainer="tnut at nutyx dot org"
depends=()
```

**Comment by peter1000** [comment]
## Pkgfile-Header

A *Pkgfile* REQUIRES a *Pkgfile-Header* in the following format:

| Required | Variable Name | Description                                         | Type |
|:--------:|:--------------|:----------------------------------------------------|:-------------------|
| YES      | `description` | A short description of the package                  | String |
| YES      | `url`         | An URL that is associated with the software package.| String |
| YES      | `maintainer`  | Name, pseudonym , e-mail address or web-link | String |
| YES      | `depends`     | A list of dependencies. | array|

**Comment by peter1000** [comment]
BTW: I did not check yet: does the c++ code of cards relay on the header or uses the variables from pkgmk.in ?

**Comment by tnut** [comment]
If I remember , The only Pkgfile variable / line cards is looking at is the:

      # Depends on line 

Means just for the compilation dependencies

**Comment by peter1000** [comment]
### REUSE cards code

I'm going to rewrite the whole `pkgmk2.in` file. To reuse some code I will split it into a separate function-library and the actual `pkgmk` file.

In this process I will also:

* rewrite some of the code:
* remove most of the code which is not essential
* try to write everything with multi-language support in mind (e.g. the option menu is still  not translatable ;)

When I'm done I will let you know - **and of course you are more than welcome to reuse anything if you want.** :+1: 

QUESTION: you used it a long time, so do you REALLY use all this options.

```
print_help() {
    echo "usage: $(basename $PKGMK_COMMAND) [options]"
    echo "options:"
    echo "   -i,  --install             build and install packages"
    echo "   -u,  --upgrade             build and install packages (as upgrade)"
    echo "   -r,  --recursive           search for and build packages recursively"
    echo "   -d,  --download            download missing source file(s)"
    echo "   -f,  --force               build packages even if it appears to be up to date"
    echo "  -cs,  --check-syntax        do not build, only check package syntax"
    echo "  -cv,  --show-version-only   do not build, only show the version of the port and exit"
    echo "  -do,  --download-only       do not build, only download missing source file(s)"
    echo "  -eo,  --extract-only        do not build, only extract source file(s)"
    echo " -utd,  --up-to-date          do not build, only check if package is up to date"
    echo "  -ur,  --update-repo         do not build, only update the $PKGMK_REPO file"
    echo "  -uc,  --update-collection   do not build, only update the $PKGMK_REPO file of the collection means from the parent directory"
    echo "  -uf,  --update-footprint    update footprint using result from last build"
    echo "  -ic,  --ignore-collection   build packages without update the $PKGMK_REPO file of the collection means from the parent directory"
    echo "  -if,  --ignore-footprint    build packages without checking footprint"
    echo "  -in,  --ignore-new          build packages, ignore new files in a footprint missmatch"
    echo "  -um,  --update-md5sum       update md5sum"
    echo "  -im,  --ignore-md5sum       build packages without checking md5sum"
    echo "  -ns,  --no-strip            do not strip executable binaries or libraries"
    echo "  -co,  --clean-only          do not build, only remove packages and downloaded files, update $PKGMK_REPO file"
    echo "  -kw,  --keep-work           keep temporary working directory"
    echo "  -cf,  --config-file <file>  use alternative configuration file"
    echo "  -v,   --version             print version and exit "
    echo "  -h,   --help                print help and exit"
}
```

My plan is: To remove everything which is not essential, and maybe add some of the features later again...

e.g. `echo "   -r,  --recursive           search for and build packages recursively"` is that really needed with cards - I thought it was used when there was still no dependency check.

**Comment by tnut** [comment]
The explaination is wrong:
Imagine that you did a collection but unfortunatly you forgot to activate the Option: PKGMK_IGNORE_REPO means no one of the compile binaries are seen by your host NuTyX as an example. With this Feature you just Need to do:

     cd /usr/ports/xfce4
     pkgmk -r -ur
     pkgmk -r -uc

I let you imagine what it does ... :+1:  yes it does it :+1:

**Comment by peter1000** [comment]
Thanks

**Comment by timcowchip** [comment]
pacman manages packages that were built with makepkg.

  

cards manages packages that were built with pkgmk.

  

> On Mar 18 2016, at 3:07 am, tnut &lt;notifications@github.com&gt; wrote:  

>

> You says: Be able to install NuTyX packages binaries with pacman package
manager. AND cards  
And then I still don't see what's this feature will bring to NuTyX. As soon
you deal with more then one PM you deal with more then one cache system
(that's just one of the side  
effects)

>

> —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly or [view it on GitHub](https://github.com/NuTyX/h
ouaphan/issues/52#issuecomment-198289075)![](https://github.com/notifications/
beacon/AHwwy3YecX_h2MQ4SHxqLDDFPWVr_Nd_ks5punlFgaJpZM4Hw8OP.gif)

**Comment by peter1000** [comment]
> timcowchip:
>
> pacman manages packages that were built with makepkg. 
> 
> cards manages packages that were built with pkgmk.
>

That's true but: the idea  was that pacman may also manage packages which are build with *cards-pkgmk* if some metadata files were added.

If it is a useful idea in the end, is a point of opinion. Would it actually work? Not sure - it is just an idea.

**Comment by timcowchip** [comment]
You should try using Crux for a while. Then you might better  appreciate what
cards does.

> On Mar 18 2016, at 11:47 am, peter1000 &lt;notifications@github.com&gt;
wrote:  

>

>> timcowchip:

>>

>> pacman manages packages that were built with makepkg.

>>

>> cards manages packages that were built with pkgmk.

>

> That's true but: the idea was that pacman may also manage packages which are
build with _cards-pkgmk_ if some metadata files were added.

>

> If it is a useful idea in the end, is a point of opinion. Would it actually
work? Not sure - it is just an idea.

>

> —  
You are receiving this because you commented.  
Reply to this email directly or [view it on GitHub](https://github.com/NuTyX/h
ouaphan/issues/52#issuecomment-198491429)![](https://github.com/notifications/
beacon/AHwwywvPOBs00U4hVzEcw5yrYo6QMf_Hks5puvM9gaJpZM4Hw8OP.gif)
